import type { ImageAsset } from "@/types/gallery";

type ImageLibraryAsset = Omit<ImageAsset, "blurDataURL">;

function createAsset(
  id: string,
  src: string,
  alt: string,
  width = 1600,
  height = 2000,
  dominantTone = "stone",
): ImageLibraryAsset {
  return {
    id,
    src,
    alt,
    width,
    height,
    dominantTone,
  };
}

export const imageAssetLibrary = {
  homeHeroVilla: createAsset(
    "home-hero-villa",
    "/images/brand/ai-temp/villa-raffaelli-dawn.webp",
    "Morning light crossing the facade of Villa Raffaelli.",
    1024,
    1536,
    "linen",
  ),
  homeCoupleQuiet: createAsset(
    "home-couple-quiet",
    "/images/brand/ai-temp/editorial-couple-loggia.webp",
    "A couple framed in quiet afternoon light among Tuscan textures.",
    1024,
    1536,
  ),
  homeReceptionNight: createAsset(
    "home-reception-night",
    "/images/brand/ai-temp/reception-evening-candles.webp",
    "A candlelit dinner scene set beneath a darkening Tuscan sky.",
    1024,
    1536,
  ),
  homeUpperTuscany: createAsset(
    "home-upper-tuscany",
    "/images/brand/ai-temp/upper-tuscany-marble-landscape.webp",
    "Upper Tuscany hills with marble-toned light and layered distance.",
    1536,
    1024,
    "sage",
  ),
  homePortraits: createAsset(
    "home-portraits",
    "/images/brand/ai-temp/portrait-studio-window-light.webp",
    "Portrait fragments shaped by artful interior light.",
    1024,
    1536,
  ),
  journalCover: createAsset(
    "journal-cover",
    "/images/brand/ai-temp/journal-garden-story.webp",
    "A couple moving through a Tuscan garden reception in late afternoon light.",
    1536,
    1024,
    "ink",
  ),
  villaCourtyard: createAsset(
    "villa-courtyard",
    "/images/brand/ai-temp/villa-courtyard-morning.webp",
    "The courtyard at Villa Raffaelli in the quiet of the morning.",
    1024,
    1536,
  ),
  luccaEvening: createAsset(
    "lucca-evening",
    "/images/brand/ai-temp/lucca-evening-garden.webp",
    "An evening celebration near Lucca with warm candlelight and depth.",
    1024,
    1536,
  ),
  marblePath: createAsset(
    "marble-path",
    "/images/brand/ai-temp/marble-ridges-distance.webp",
    "Layered mountain light and marble-toned ridges above the coast.",
    1536,
    1024,
  ),
  intimateGesture: createAsset(
    "intimate-gesture",
    "/images/brand/ai-temp/intimate-gesture-garden.webp",
    "An intimate gesture between partners in a calm editorial frame.",
    1024,
    1536,
  ),
  studioInterior: createAsset(
    "studio-interior",
    "/images/brand/ai-temp/portrait-studio-window-light.webp",
    "A quiet portrait fragment inside the studio world of Villa Raffaelli.",
    1024,
    1536,
  ),
  storyFrame: createAsset(
    "story-frame",
    "/images/brand/ai-temp/journal-garden-story.webp",
    "A layered editorial story image used across journal previews.",
    1536,
    1024,
  ),
  florenceLoggiaBlueHour: createAsset(
    "florence-loggia-blue-hour",
    "/images/brand/ai-temp/florence-loggia-blue-hour.webp",
    "A couple beneath a Renaissance loggia in Florence at blue hour.",
    1024,
    1536,
    "ink",
  ),
  sienaCourtyardPortrait: createAsset(
    "siena-courtyard-portrait",
    "/images/brand/ai-temp/siena-courtyard-portrait.webp",
    "A bride moving through a quiet Siena courtyard in late-afternoon light.",
    1024,
    1536,
    "stone",
  ),
  chiantiVineyardDinner: createAsset(
    "chianti-vineyard-dinner",
    "/images/brand/ai-temp/chianti-vineyard-dinner.webp",
    "A long candlelit wedding dinner among vines in Chianti at dusk.",
    1536,
    1024,
    "olive",
  ),
  valDorciaCypressVows: createAsset(
    "val-dorcia-cypress-vows",
    "/images/brand/ai-temp/val-dorcia-cypress-vows.webp",
    "A couple exchanging vows above the cypress-lined landscape of Val d'Orcia.",
    1536,
    1024,
    "linen",
  ),
  oliveGardenCeremony: createAsset(
    "olive-garden-ceremony",
    "/images/brand/ai-temp/olive-garden-ceremony.webp",
    "An intimate ceremony beneath olive trees in Tuscany.",
    1536,
    1024,
    "sage",
  ),
  bridalPrepWindowSilk: createAsset(
    "bridal-prep-window-silk",
    "/images/brand/ai-temp/bridal-prep-window-silk.webp",
    "A bride by a tall window in the quiet of morning preparation.",
    1024,
    1536,
    "linen",
  ),
  villaLibraryPortrait: createAsset(
    "villa-library-portrait",
    "/images/brand/ai-temp/villa-library-portrait.webp",
    "A couple in the library world of Villa Raffaelli in soft morning light.",
    1024,
    1536,
    "stone",
  ),
  villaPrivateCourtyardWedding: createAsset(
    "villa-private-courtyard-wedding",
    "/images/brand/villa-generated/villa-raffaelli-private-courtyard-wedding.webp",
    "Two people exchanging private wedding vows in the courtyard of Villa Raffaelli.",
    1536,
    1024,
    "stone",
  ),
  villaNewlywedsMountainGarden: createAsset(
    "villa-newlyweds-mountain-garden",
    "/images/brand/villa-generated/villa-raffaelli-newlyweds-mountain-garden.webp",
    "Two newly married partners walking through the Villa Raffaelli garden with Garfagnana mountains behind them.",
    1024,
    1536,
    "sage",
  ),
  versiliaSeasideWalk: createAsset(
    "versilia-seaside-walk",
    "/images/brand/ai-temp/versilia-seaside-walk.webp",
    "A couple walking the Versilia shoreline in soft coastal dusk.",
    1536,
    1024,
    "ink",
  ),
  candlelitCourtyardToast: createAsset(
    "candlelit-courtyard-toast",
    "/images/brand/ai-temp/candlelit-courtyard-toast.webp",
    "A candlelit toast in a Tuscan stone courtyard.",
    1024,
    1536,
    "ink",
  ),
  welcomeDinnerLanterns: createAsset(
    "welcome-dinner-lanterns",
    "/images/brand/ai-temp/welcome-dinner-lanterns.webp",
    "A welcome dinner beneath lanterns and cypress silhouettes in Tuscany.",
    1536,
    1024,
    "olive",
  ),
  film35mmRollStillLife: createAsset(
    "film-35mm-roll-still-life",
    "/images/brand/film-generated/35mm-film-roll-still-life.webp",
    "A 35mm film roll styled on a weathered studio table with loupe and exposure notes.",
    1024,
    1536,
    "stone",
  ),
  film120RollStyling: createAsset(
    "film-120-roll-styling",
    "/images/brand/film-generated/120-film-roll-styling.webp",
    "A 120 medium format film roll on a refined wedding styling surface.",
    1024,
    1536,
    "linen",
  ),
  film4x5SheetHolder: createAsset(
    "film-4x5-sheet-holder",
    "/images/brand/film-generated/4x5-sheet-film-box-holder.webp",
    "A 4x5 sheet film box and holder on a serious analog studio workbench.",
    1536,
    1024,
    "ink",
  ),
  filmNikonFVintageVillaLibrary: createAsset(
    "film-nikon-f-vintage-villa-library",
    "/images/brand/film-generated/nikon-f-vintage-villa-library.webp",
    "A vintage Nikon F camera resting in the library atmosphere of a Tuscan villa.",
    1024,
    1536,
    "stone",
  ),
  filmNikonF5ReceptionCorner: createAsset(
    "film-nikon-f5-reception-corner",
    "/images/brand/film-generated/nikon-f5-reception-corner.webp",
    "A Nikon F5 camera styled beside candlelight and florals at a Tuscan reception.",
    1024,
    1536,
    "ink",
  ),
  filmRolleiflexBridalPrep: createAsset(
    "film-rolleiflex-bridal-prep",
    "/images/brand/film-generated/rolleiflex-35-bridal-prep.webp",
    "A Rolleiflex camera on a bridal preparation table with silk details and morning light.",
    1024,
    1536,
    "linen",
  ),
  filmHasselblad500cmWindowGarden: createAsset(
    "film-hasselblad-500cm-window-garden",
    "/images/brand/film-generated/hasselblad-500cm-window-garden.webp",
    "A Hasselblad 500cm on a stone windowsill above a Tuscan wedding garden.",
    1024,
    1536,
    "sage",
  ),
  film8x10ViewCameraOliveGrove: createAsset(
    "film-8x10-view-camera-olive-grove",
    "/images/brand/film-generated/8x10-view-camera-olive-grove.webp",
    "A black wooden 8x10 view camera standing in an olive grove wedding location.",
    1024,
    1536,
    "olive",
  ),
  filmSmartflex4x5Courtyard: createAsset(
    "film-smartflex-4x5-courtyard",
    "/images/brand/film-generated/smartflex-4x5-courtyard.webp",
    "A 4x5 Graflex-like Smartflex camera at the edge of a Tuscan stone courtyard.",
    1024,
    1536,
    "stone",
  ),
  filmHasselbladGroundGlassOliveCeremony: createAsset(
    "film-hasselblad-ground-glass-olive-ceremony",
    "/images/brand/film-generated/hasselblad-ground-glass-olive-ceremony.webp",
    "A Hasselblad ground-glass view of a couple beneath olive trees during a Tuscany ceremony.",
    1536,
    1024,
    "olive",
  ),
  filmHasselbladGroundGlassBridalWindow: createAsset(
    "film-hasselblad-ground-glass-bridal-window",
    "/images/brand/film-generated/hasselblad-ground-glass-bridal-window.webp",
    "A Hasselblad ground-glass view of a bride by a tall villa window.",
    1536,
    1024,
    "linen",
  ),
  filmHasselbladGroundGlassReception: createAsset(
    "film-hasselblad-ground-glass-reception",
    "/images/brand/film-generated/hasselblad-ground-glass-reception.webp",
    "A Hasselblad ground-glass view of a candlelit wedding dinner in Tuscany.",
    1536,
    1024,
    "ink",
  ),
  darkroomHangingPrintsRedLight: createAsset(
    "darkroom-hanging-prints-red-light",
    "/images/brand/film-generated/darkroom-hanging-prints-red-light.webp",
    "A working darkroom under red safelight with wedding prints hanging to dry.",
    1536,
    1024,
    "ink",
  ),
  darkroomChemistryTraysHands: createAsset(
    "darkroom-chemistry-trays-hands",
    "/images/brand/film-generated/darkroom-chemistry-trays-hands.webp",
    "Gloved hands moving photographic paper through chemistry trays in a red-lit darkroom.",
    1536,
    1024,
    "ink",
  ),
  darkroomEnlargerWorkbench: createAsset(
    "darkroom-enlarger-workbench",
    "/images/brand/film-generated/darkroom-enlarger-workbench.webp",
    "A classic enlarger and darkroom tools arranged on a professional workbench.",
    1536,
    1024,
    "ink",
  ),
  darkroomFilmShelvesTools: createAsset(
    "darkroom-film-shelves-tools",
    "/images/brand/film-generated/darkroom-film-shelves-tools.webp",
    "Darkroom shelves holding film canisters, reels, and analog tools under safelight.",
    1536,
    1024,
    "ink",
  ),
  filmCameraCollectionStudioTable: createAsset(
    "film-camera-collection-studio-table",
    "/images/brand/film-generated/film-camera-collection-studio-table.webp",
    "A curated table of film cameras and film formats inside the Dolcevilla analog studio world.",
    1536,
    1024,
    "stone",
  ),
  darkroomSinkPrintsPortrait: createAsset(
    "darkroom-sink-prints-portrait",
    "/images/brand/film-generated/darkroom-sink-prints-portrait.webp",
    "A portrait view of the darkroom sink area with trays, prints, and red safelight.",
    1024,
    1536,
    "ink",
  ),
  journalCastelloVincigliataGuideCover: createAsset(
    "journal-castello-vincigliata-guide-cover",
    "/images/brand/journal-generated/castello-di-vincigliata-wedding-guide-venue-logistics-and-guest-experience-cover.png",
    "Wedding guests entering the stone courtyard of Castello di Vincigliata in late-afternoon light.",
    1600,
    900,
    "stone",
  ),
  journalCastelloVincigliataGuideOrnamentWash: createAsset(
    "journal-castello-vincigliata-guide-ornament-wash",
    "/images/brand/journal-generated/castello-di-vincigliata-wedding-guide-venue-logistics-and-guest-experience-ornament-wash.png",
    "A textured journal ornament with castle arches, cypress forms, and a winding approach road.",
    1600,
    900,
    "stone",
  ),
  journalCastelloVincigliataGuideOrnamentOrbit: createAsset(
    "journal-castello-vincigliata-guide-ornament-orbit",
    "/images/brand/journal-generated/castello-di-vincigliata-wedding-guide-venue-logistics-and-guest-experience-ornament-orbit.png",
    "A small textured journal ornament with a castle arch, olive leaves, and a looping arrival path.",
    1600,
    900,
    "stone",
  ),
  journalVillaGrabauGuideCover: createAsset(
    "journal-villa-grabau-guide-cover",
    "/images/brand/journal-generated/villa-grabau-wedding-guide-why-lucca-couples-keep-shortlisting-it-cover.png",
    "A couple and guests walking through the formal approach garden of a historic Lucca villa in late-afternoon light.",
    1600,
    900,
    "stone",
  ),
  journalVillaGrabauGuideOrnamentWash: createAsset(
    "journal-villa-grabau-guide-ornament-wash",
    "/images/brand/journal-generated/villa-grabau-wedding-guide-why-lucca-couples-keep-shortlisting-it-ornament-wash.png",
    "A textured journal ornament with clipped hedges, lemonhouse arches, botanical silhouettes, and pale stone forms.",
    1600,
    900,
    "stone",
  ),
  journalVillaGrabauGuideOrnamentOrbit: createAsset(
    "journal-villa-grabau-guide-ornament-orbit",
    "/images/brand/journal-generated/villa-grabau-wedding-guide-why-lucca-couples-keep-shortlisting-it-ornament-orbit.png",
    "A small textured journal ornament with a cypress form, lemon accent, hedge-theatre curve, and arched window motif.",
    1600,
    900,
    "stone",
  ),
  journalVillaCatignanoPhotographerCover: createAsset(
    "journal-villa-catignano-photographer-cover",
    "/images/brand/journal-generated/villa-catignano-wedding-photographer-in-castelnuovo-berardenga-cover.png",
    "A wedding couple centered on the broad garden steps of a formal Chianti villa with lemon trees, cypress rhythm, and late-afternoon sky.",
    1600,
    900,
    "stone",
  ),
  journalVillaCatignanoPhotographerOrnamentWash: createAsset(
    "journal-villa-catignano-photographer-ornament-wash",
    "/images/brand/journal-generated/villa-catignano-wedding-photographer-in-castelnuovo-berardenga-ornament-wash.png",
    "A textured journal ornament with clipped hedge parterres, terracotta lemon pots, cypress silhouettes, and pale stone steps.",
    1600,
    900,
    "stone",
  ),
  journalVillaCatignanoPhotographerOrnamentOrbit: createAsset(
    "journal-villa-catignano-photographer-ornament-orbit",
    "/images/brand/journal-generated/villa-catignano-wedding-photographer-in-castelnuovo-berardenga-ornament-orbit.png",
    "A small textured journal ornament with a cypress form, looping garden path, lemon branch, and classical garden statue.",
    1600,
    900,
    "stone",
  ),
  journalVillaVsCastleWeddingCover: createAsset(
    "journal-villa-vs-castle-wedding-cover",
    "/images/brand/journal-generated/villa-vs-castle-wedding-in-tuscany-style-budget-and-guest-experience-cover.png",
    "A wedding couple centered in a gravel forecourt between a pale Tuscan villa facade and a crenellated stone gate at dusk.",
    1600,
    900,
    "stone",
  ),
  journalVillaVsCastleWeddingOrnamentWash: createAsset(
    "journal-villa-vs-castle-wedding-ornament-wash",
    "/images/brand/journal-generated/villa-vs-castle-wedding-in-tuscany-style-budget-and-guest-experience-ornament-wash.png",
    "A textured journal ornament with pale villa planes, cypress silhouettes, battlement curves, stone arch forms, and a gravel-path rhythm.",
    1600,
    900,
    "stone",
  ),
  journalVillaVsCastleWeddingOrnamentOrbit: createAsset(
    "journal-villa-vs-castle-wedding-ornament-orbit",
    "/images/brand/journal-generated/villa-vs-castle-wedding-in-tuscany-style-budget-and-guest-experience-ornament-orbit.png",
    "A small textured journal ornament with a crenellated tower, cypress form, looping path, and pale villa arch detail.",
    1600,
    900,
    "stone",
  ),
  journalTuscanyPhotographerFilmFlashBackupCover: createAsset(
    "journal-tuscany-photographer-film-flash-backup-cover",
    "/images/brand/journal-generated/questions-to-ask-a-tuscany-wedding-photographer-about-film-flash-and-backup-gear-cover.png",
    "A wedding couple walking a narrow Tuscan hill path at blue hour while a photographer tests flash behind them.",
    1600,
    900,
    "ink",
  ),
  journalTuscanyPhotographerFilmFlashBackupOrnamentWash: createAsset(
    "journal-tuscany-photographer-film-flash-backup-ornament-wash",
    "/images/brand/journal-generated/questions-to-ask-a-tuscany-wedding-photographer-about-film-flash-and-backup-gear-ornament-wash.png",
    "A textured journal ornament with a film-reel arc, winding path, cypress silhouettes, flash halo, and structured backup-case forms.",
    1600,
    900,
    "ink",
  ),
  journalTuscanyPhotographerFilmFlashBackupOrnamentOrbit: createAsset(
    "journal-tuscany-photographer-film-flash-backup-ornament-orbit",
    "/images/brand/journal-generated/questions-to-ask-a-tuscany-wedding-photographer-about-film-flash-and-backup-gear-ornament-orbit.png",
    "A small textured journal ornament with a looping path ribbon, flash burst, film strip curve, and compact backup-case blocks.",
    1600,
    900,
    "ink",
  ),
  journalTuscanyWeddingWeekendCostCover: createAsset(
    "journal-tuscany-wedding-weekend-cost-cover",
    "/images/brand/journal-generated/how-much-does-a-wedding-weekend-in-tuscany-cost-cover.png",
    "A wedding couple centered on a long Tuscan dinner terrace while staff make final preparations in airy late-afternoon light.",
    1600,
    900,
    "linen",
  ),
  journalTuscanyWeddingWeekendCostOrnamentWash: createAsset(
    "journal-tuscany-wedding-weekend-cost-ornament-wash",
    "/images/brand/journal-generated/how-much-does-a-wedding-weekend-in-tuscany-cost-ornament-wash.png",
    "A textured journal ornament with a long dinner-table ribbon, cypress hills, terrace planters, floral clusters, and warm hospitality shapes.",
    1600,
    900,
    "linen",
  ),
  journalTuscanyWeddingWeekendCostOrnamentOrbit: createAsset(
    "journal-tuscany-wedding-weekend-cost-ornament-orbit",
    "/images/brand/journal-generated/how-much-does-a-wedding-weekend-in-tuscany-cost-ornament-orbit.png",
    "A small textured journal ornament with a looping table ribbon, candle-like circle, cypress forms, and a terrace arch.",
    1600,
    900,
    "linen",
  ),
  journalPienzaWeddingPhotographerValDOrciaWeddingCover: createAsset(
    "journal-pienza-wedding-photographer-val-dorcia-wedding-cover",
    "/images/brand/journal-generated/pienza-wedding-photographer-for-a-val-dorcia-wedding-cover.png",
    "A couple holding a bouquet and wind-lifted veil on a pale stone Pienza terrace above the soft Val d'Orcia landscape.",
    1600,
    900,
    "stone",
  ),
  journalPienzaWeddingPhotographerValDOrciaWeddingOrnamentWash: createAsset(
    "journal-pienza-wedding-photographer-val-dorcia-wedding-ornament-wash",
    "/images/brand/journal-generated/pienza-wedding-photographer-for-a-val-dorcia-wedding-ornament-wash.png",
    "A textured journal ornament with a pale stone parapet, veil ribbon, cypress silhouettes, valley contours, and blush florals.",
    1600,
    900,
    "stone",
  ),
  journalPienzaWeddingPhotographerValDOrciaWeddingOrnamentOrbit: createAsset(
    "journal-pienza-wedding-photographer-val-dorcia-wedding-ornament-orbit",
    "/images/brand/journal-generated/pienza-wedding-photographer-for-a-val-dorcia-wedding-ornament-orbit.png",
    "A small textured journal ornament with a stone arch fragment, cypress silhouettes, veil ribbon, bouquet, and warm sun disk.",
    1600,
    900,
    "stone",
  ),
  journalMontepulcianoWeddingPhotographerDestinationWeddingTuscanyCover: createAsset(
    "journal-montepulciano-wedding-photographer-destination-wedding-tuscany-cover",
    "/images/brand/journal-generated/montepulciano-wedding-photographer-for-a-destination-wedding-in-tuscany-cover.png",
    "Interlocked wedding hands, veil, and ceremony paper resting on a Montepulciano stone parapet above soft vineyard blur.",
    1600,
    900,
    "stone",
  ),
  journalMontepulcianoWeddingPhotographerDestinationWeddingTuscanyOrnamentWash: createAsset(
    "journal-montepulciano-wedding-photographer-destination-wedding-tuscany-ornament-wash",
    "/images/brand/journal-generated/montepulciano-wedding-photographer-for-a-destination-wedding-in-tuscany-ornament-wash.png",
    "A textured journal ornament with a Montepulciano stone balustrade, veil ribbon, vineyard rows, warm sun disk, and old-town silhouette.",
    1600,
    900,
    "stone",
  ),
  journalMontepulcianoWeddingPhotographerDestinationWeddingTuscanyOrnamentOrbit: createAsset(
    "journal-montepulciano-wedding-photographer-destination-wedding-tuscany-ornament-orbit",
    "/images/brand/journal-generated/montepulciano-wedding-photographer-for-a-destination-wedding-in-tuscany-ornament-orbit.png",
    "A small textured journal ornament with a stone arch, olive sprig, veil loop, hillside town silhouette, and vineyard curves.",
    1600,
    900,
    "stone",
  ),
  journalSuper8WelcomePartyDigitalWeddingDayCover: createAsset(
    "journal-super8-welcome-party-digital-wedding-day-cover",
    "/images/brand/journal-generated/super-8-for-the-welcome-party-digital-for-the-wedding-day-a-smart-tuscany-coverage-mix-cover.png",
    "A hand lifting a compact Super 8 camera above a pale linen welcome-party table in airy Tuscany light.",
    1600,
    900,
    "linen",
  ),
  journalSuper8WelcomePartyDigitalWeddingDayOrnamentWash: createAsset(
    "journal-super8-welcome-party-digital-wedding-day-ornament-wash",
    "/images/brand/journal-generated/super-8-for-the-welcome-party-digital-for-the-wedding-day-a-smart-tuscany-coverage-mix-ornament-wash.png",
    "A textured journal ornament with a looping film ribbon, olive branch, coupe arc, pale stone forms, and flowing linen band.",
    1600,
    900,
    "linen",
  ),
  journalSuper8WelcomePartyDigitalWeddingDayOrnamentOrbit: createAsset(
    "journal-super8-welcome-party-digital-wedding-day-ornament-orbit",
    "/images/brand/journal-generated/super-8-for-the-welcome-party-digital-for-the-wedding-day-a-smart-tuscany-coverage-mix-ornament-orbit.png",
    "A small textured journal ornament with a film loop, camera-strap arc, olive sprig, coupe curve, and warm sun disk.",
    1600,
    900,
    "linen",
  ),
  journalIndoorEngagementSessionsTuscanyCover: createAsset(
    "journal-indoor-engagement-sessions-tuscany-cover",
    "/images/brand/journal-generated/indoor-engagement-sessions-in-tuscany-bars-hotels-and-historic-interiors-cover.png",
    "A ringed hand steadying a coupe glass on a marble table inside a faded historic Tuscan hotel bar.",
    1600,
    900,
    "stone",
  ),
  journalIndoorEngagementSessionsTuscanyOrnamentWash: createAsset(
    "journal-indoor-engagement-sessions-tuscany-ornament-wash",
    "/images/brand/journal-generated/indoor-engagement-sessions-in-tuscany-bars-hotels-and-historic-interiors-ornament-wash.png",
    "A textured journal ornament with a coupe-glass outline, marble curve, aged mirror panels, velvet drape, and brass edge.",
    1600,
    900,
    "stone",
  ),
  journalIndoorEngagementSessionsTuscanyOrnamentOrbit: createAsset(
    "journal-indoor-engagement-sessions-tuscany-ornament-orbit",
    "/images/brand/journal-generated/indoor-engagement-sessions-in-tuscany-bars-hotels-and-historic-interiors-ornament-orbit.png",
    "A small textured journal ornament with a coupe-rim line, brass oval, mirror panel, and soft velvet ribbon.",
    1600,
    900,
    "stone",
  ),
  journalWhyAfterPartyCoverageMattersTuscanyCover: createAsset(
    "journal-why-after-party-coverage-matters-tuscany-cover",
    "/images/brand/journal-generated/why-after-party-coverage-matters-at-a-tuscany-destination-wedding-cover.png",
    "A mirrored disco ball hanging in a dark Tuscan reception room under direct flash.",
    1600,
    900,
    "stone",
  ),
  journalWhyAfterPartyCoverageMattersTuscanyOrnamentWash: createAsset(
    "journal-why-after-party-coverage-matters-tuscany-ornament-wash",
    "/images/brand/journal-generated/why-after-party-coverage-matters-at-a-tuscany-destination-wedding-ornament-wash.png",
    "A textured journal ornament with a disco-ball arc, ribbon sweep, tiled mirror marks, and pale after-party linen.",
    1600,
    900,
    "stone",
  ),
  journalWhyAfterPartyCoverageMattersTuscanyOrnamentOrbit: createAsset(
    "journal-why-after-party-coverage-matters-tuscany-ornament-orbit",
    "/images/brand/journal-generated/why-after-party-coverage-matters-at-a-tuscany-destination-wedding-ornament-orbit.png",
    "A small textured journal ornament with a disco-ball oval, flash ring, ribbon loop, and warm light dots.",
    1600,
    900,
    "stone",
  ),
  journalCivilWeddingsTuscanyLegalCover: createAsset(
    "journal-civil-weddings-tuscany-legal-cover",
    "/images/brand/journal-generated/civil-weddings-in-tuscany-where-you-can-legally-get-married-cover.png",
    "Red-upholstered civic chairs inside Sala Rossa at Palazzo Vecchio before a civil ceremony begins.",
    1600,
    900,
    "stone",
  ),
  journalCivilWeddingsTuscanyLegalOrnamentWash: createAsset(
    "journal-civil-weddings-tuscany-legal-ornament-wash",
    "/images/brand/journal-generated/civil-weddings-in-tuscany-where-you-can-legally-get-married-ornament-wash.png",
    "A textured journal ornament with a civic arch, red chair rhythm, signing-table band, and ceremonial ribbon.",
    1600,
    900,
    "stone",
  ),
  journalCivilWeddingsTuscanyLegalOrnamentOrbit: createAsset(
    "journal-civil-weddings-tuscany-legal-ornament-orbit",
    "/images/brand/journal-generated/civil-weddings-in-tuscany-where-you-can-legally-get-married-ornament-orbit.png",
    "A small textured journal ornament with a chair-back arch, seal circle, ribbon loop, and pale civic lines.",
    1600,
    900,
    "stone",
  ),
  teamLisaMazzei: createAsset(
    "team-lisa-mazzei",
    "/images/brand/team/lisa-mazzei-headshot.webp",
    "Editorial headshot of Lisa Mazzei against a warm textured studio backdrop.",
    960,
    1440,
    "stone",
  ),
  teamAlbertoPellegrinetti: createAsset(
    "team-alberto-pellegrinetti",
    "/images/brand/team/alberto-pellegrinetti-headshot.webp",
    "Editorial headshot of Alberto Pellegrinetti against a warm textured studio backdrop.",
    960,
    1440,
    "stone",
  ),
  teamLeonardoFiori: createAsset(
    "team-leonardo-fiori",
    "/images/brand/team/leonardo-fiori-headshot.webp",
    "Editorial headshot of Leonardo Fiori against a warm textured studio backdrop.",
    960,
    1440,
    "stone",
  ),
  teamFrancescoTarantino: createAsset(
    "team-francesco-tarantino",
    "/images/brand/team/francesco-tarantino-headshot.webp",
    "Editorial headshot of Francesco Tarantino against a warm textured studio backdrop.",
    960,
    1440,
    "stone",
  ),
  teamWiderStudioVillaRaffaelli: createAsset(
    "team-wider-studio-villa-raffaelli",
    "/images/brand/team/wider-studio-villa-raffaelli.webp",
    "A monochrome architectural sketch of Villa Raffaelli above Tuscan stone steps.",
    1024,
    1536,
    "stone",
  ),
  homeHeroPrimaryGenerated: createAsset(
    "page-home-hero-primary",
    "/images/brand/page-generated/page-home-hero-primary.webp",
    "Morning light crossing the facade of Villa Raffaelli.",
    1600,
    900,
    "linen",
  ),
  homeHeroSecondaryGenerated: createAsset(
    "page-home-hero-secondary",
    "/images/brand/page-generated/page-home-hero-secondary.webp",
    "The courtyard at Villa Raffaelli in the quiet of the morning.",
    1600,
    900,
    "stone",
  ),
  homeHeroTertiaryGenerated: createAsset(
    "page-home-hero-tertiary",
    "/images/brand/page-generated/page-home-hero-tertiary.webp",
    "A couple framed in quiet afternoon light among Tuscan textures.",
    1600,
    900,
    "stone",
  ),
  homeHeroQuaternaryGenerated: createAsset(
    "page-home-hero-quaternary",
    "/images/brand/page-generated/page-home-hero-quaternary.webp",
    "A couple in the library world of Villa Raffaelli in soft morning light.",
    1600,
    900,
    "stone",
  ),
  homeGallery1Generated: createAsset(
    "page-home-gallery-1",
    "/images/brand/page-generated/page-home-gallery-1.webp",
    "A couple framed in quiet afternoon light among Tuscan textures.",
    1024,
    1536,
    "stone",
  ),
  homeGallery2Generated: createAsset(
    "page-home-gallery-2",
    "/images/brand/page-generated/page-home-gallery-2.webp",
    "An intimate ceremony beneath olive trees in Tuscany.",
    1536,
    1024,
    "sage",
  ),
  homeGallery3Generated: createAsset(
    "page-home-gallery-3",
    "/images/brand/page-generated/page-home-gallery-3.webp",
    "The courtyard at Villa Raffaelli in the quiet of the morning.",
    1024,
    1536,
    "stone",
  ),
  homeGallery4Generated: createAsset(
    "page-home-gallery-4",
    "/images/brand/page-generated/page-home-gallery-4.webp",
    "A welcome dinner beneath lanterns and cypress silhouettes in Tuscany.",
    1536,
    1024,
    "olive",
  ),
  homeGallery5Generated: createAsset(
    "page-home-gallery-5",
    "/images/brand/page-generated/page-home-gallery-5.webp",
    "A couple beneath a Renaissance loggia in Florence at blue hour.",
    1024,
    1536,
    "ink",
  ),
  homeGallery6Generated: createAsset(
    "page-home-gallery-6",
    "/images/brand/page-generated/page-home-gallery-6.webp",
    "A couple exchanging vows above the cypress-lined landscape of Val d'Orcia.",
    1536,
    1024,
    "linen",
  ),
  homeCraftImageGenerated: createAsset(
    "page-home-craft-image",
    "/images/brand/page-generated/page-home-craft-image.webp",
    "A Rolleiflex camera on a bridal preparation table with silk details and morning light.",
    1120,
    1400,
    "linen",
  ),
  homeVillaImageGenerated: createAsset(
    "page-home-villa-image",
    "/images/brand/page-generated/page-home-villa-image.webp",
    "Morning light crossing the facade of Villa Raffaelli.",
    1400,
    1120,
    "linen",
  ),
  aboutHeroPrimaryGenerated: createAsset(
    "page-about-hero-primary",
    "/images/brand/page-generated/page-about-hero-primary.webp",
    "A couple in the library world of Villa Raffaelli in soft morning light.",
    1600,
    900,
    "stone",
  ),
  aboutHeroSecondaryGenerated: createAsset(
    "page-about-hero-secondary",
    "/images/brand/page-generated/page-about-hero-secondary.webp",
    "A couple framed in quiet afternoon light among Tuscan textures.",
    1600,
    900,
    "stone",
  ),
  aboutHeroTertiaryGenerated: createAsset(
    "page-about-hero-tertiary",
    "/images/brand/page-generated/page-about-hero-tertiary.webp",
    "The courtyard at Villa Raffaelli in the quiet of the morning.",
    1600,
    900,
    "stone",
  ),
  aboutTeamLisaGenerated: createAsset(
    "page-about-team-lisa",
    "/images/brand/page-generated/page-about-team-lisa.webp",
    "Editorial headshot of Lisa Mazzei against a warm textured studio backdrop.",
    1120,
    1400,
    "stone",
  ),
  aboutTeamAlbertoGenerated: createAsset(
    "page-about-team-alberto",
    "/images/brand/page-generated/page-about-team-alberto.webp",
    "Editorial headshot of Alberto Pellegrinetti against a warm textured studio backdrop.",
    1120,
    1400,
    "stone",
  ),
  aboutTeamLeonardoGenerated: createAsset(
    "page-about-team-leonardo",
    "/images/brand/page-generated/page-about-team-leonardo.webp",
    "Editorial headshot of Leonardo Fiori against a warm textured studio backdrop.",
    1120,
    1400,
    "stone",
  ),
  aboutTeamFrancescoGenerated: createAsset(
    "page-about-team-francesco",
    "/images/brand/page-generated/page-about-team-francesco.webp",
    "Editorial headshot of Francesco Tarantino against a warm textured studio backdrop.",
    1120,
    1400,
    "stone",
  ),
  aboutGallery1Generated: createAsset(
    "page-about-gallery-1",
    "/images/brand/page-generated/page-about-gallery-1.webp",
    "A 35mm film roll styled on a weathered studio table with loupe and exposure notes.",
    1024,
    1536,
    "stone",
  ),
  aboutGallery2Generated: createAsset(
    "page-about-gallery-2",
    "/images/brand/page-generated/page-about-gallery-2.webp",
    "A 120 medium format film roll on a refined wedding styling surface.",
    1024,
    1536,
    "linen",
  ),
  aboutGallery3Generated: createAsset(
    "page-about-gallery-3",
    "/images/brand/page-generated/page-about-gallery-3.webp",
    "A 4x5 sheet film box and holder on a serious analog studio workbench.",
    1536,
    1024,
    "ink",
  ),
  aboutGallery4Generated: createAsset(
    "page-about-gallery-4",
    "/images/brand/page-generated/page-about-gallery-4.webp",
    "A curated table of film cameras and film formats inside the Dolcevilla analog studio world.",
    1536,
    1024,
    "stone",
  ),
  aboutGallery5Generated: createAsset(
    "page-about-gallery-5",
    "/images/brand/page-generated/page-about-gallery-5.webp",
    "Darkroom shelves holding film canisters, reels, and analog tools under safelight.",
    1536,
    1024,
    "ink",
  ),
  aboutGallery6Generated: createAsset(
    "page-about-gallery-6",
    "/images/brand/page-generated/page-about-gallery-6.webp",
    "A portrait view of the darkroom sink area with trays, prints, and red safelight.",
    1024,
    1536,
    "ink",
  ),
  aboutCraftImageGenerated: createAsset(
    "page-about-craft-image",
    "/images/brand/page-generated/page-about-craft-image.webp",
    "A curated table of film cameras and film formats inside the Dolcevilla analog studio world.",
    1120,
    1400,
    "stone",
  ),
  aboutVillaImageGenerated: createAsset(
    "page-about-villa-image",
    "/images/brand/page-generated/page-about-villa-image.webp",
    "Morning light crossing the facade of Villa Raffaelli.",
    1400,
    1120,
    "linen",
  ),
  experienceGallery1Generated: createAsset(
    "page-experience-gallery-1",
    "/images/brand/page-generated/page-experience-gallery-1.webp",
    "A Nikon F5 camera styled beside candlelight and florals at a Tuscan reception.",
    1024,
    1536,
    "ink",
  ),
  experienceGallery2Generated: createAsset(
    "page-experience-gallery-2",
    "/images/brand/page-generated/page-experience-gallery-2.webp",
    "A Hasselblad ground-glass view of a bride by a tall villa window.",
    1536,
    1024,
    "linen",
  ),
  experienceGallery3Generated: createAsset(
    "page-experience-gallery-3",
    "/images/brand/page-generated/page-experience-gallery-3.webp",
    "A Hasselblad ground-glass view of a candlelit wedding dinner in Tuscany.",
    1536,
    1024,
    "ink",
  ),
  experienceGallery4Generated: createAsset(
    "page-experience-gallery-4",
    "/images/brand/page-generated/page-experience-gallery-4.webp",
    "A 4x5 Graflex-like Smartflex camera at the edge of a Tuscan stone courtyard.",
    1024,
    1536,
    "stone",
  ),
  experienceCraftImageGenerated: createAsset(
    "page-experience-craft-image",
    "/images/brand/page-generated/page-experience-craft-image.webp",
    "A Hasselblad ground-glass view of a bride by a tall villa window.",
    1120,
    1400,
    "linen",
  ),
  experienceVillaImageGenerated: createAsset(
    "page-experience-villa-image",
    "/images/brand/page-generated/page-experience-villa-image.webp",
    "Morning light crossing the facade of Villa Raffaelli.",
    1400,
    1120,
    "linen",
  ),
  filmWeddingPhotographyHeroPrimaryGenerated: createAsset(
    "page-film-wedding-photography-hero-primary",
    "/images/brand/page-generated/page-film-wedding-photography-hero-primary.webp",
    "A couple in the library world of Villa Raffaelli in soft morning light.",
    1600,
    900,
    "stone",
  ),
  filmWeddingPhotographyHeroSecondaryGenerated: createAsset(
    "page-film-wedding-photography-hero-secondary",
    "/images/brand/page-generated/page-film-wedding-photography-hero-secondary.webp",
    "A couple framed in quiet afternoon light among Tuscan textures.",
    1600,
    900,
    "stone",
  ),
  filmWeddingPhotographyHeroTertiaryGenerated: createAsset(
    "page-film-wedding-photography-hero-tertiary",
    "/images/brand/page-generated/page-film-wedding-photography-hero-tertiary.webp",
    "Morning light crossing the facade of Villa Raffaelli.",
    1600,
    900,
    "linen",
  ),
  filmWeddingPhotographyHeroQuaternaryGenerated: createAsset(
    "page-film-wedding-photography-hero-quaternary",
    "/images/brand/page-generated/page-film-wedding-photography-hero-quaternary.webp",
    "The courtyard at Villa Raffaelli in the quiet of the morning.",
    1600,
    900,
    "stone",
  ),
  filmWeddingPhotographyGallery1Generated: createAsset(
    "page-film-wedding-photography-gallery-1",
    "/images/brand/page-generated/page-film-wedding-photography-gallery-1.webp",
    "A 35mm film roll styled on a weathered studio table with loupe and exposure notes.",
    1024,
    1536,
    "stone",
  ),
  filmWeddingPhotographyGallery2Generated: createAsset(
    "page-film-wedding-photography-gallery-2",
    "/images/brand/page-generated/page-film-wedding-photography-gallery-2.webp",
    "A vintage Nikon F camera resting in the library atmosphere of a Tuscan villa.",
    1024,
    1536,
    "stone",
  ),
  filmWeddingPhotographyGallery3Generated: createAsset(
    "page-film-wedding-photography-gallery-3",
    "/images/brand/page-generated/page-film-wedding-photography-gallery-3.webp",
    "A Nikon F5 camera styled beside candlelight and florals at a Tuscan reception.",
    1024,
    1536,
    "ink",
  ),
  filmWeddingPhotographyGallery4Generated: createAsset(
    "page-film-wedding-photography-gallery-4",
    "/images/brand/page-generated/page-film-wedding-photography-gallery-4.webp",
    "A 120 medium format film roll on a refined wedding styling surface.",
    1024,
    1536,
    "linen",
  ),
  filmWeddingPhotographyGallery5Generated: createAsset(
    "page-film-wedding-photography-gallery-5",
    "/images/brand/page-generated/page-film-wedding-photography-gallery-5.webp",
    "A Rolleiflex camera on a bridal preparation table with silk details and morning light.",
    1024,
    1536,
    "linen",
  ),
  filmWeddingPhotographyGallery6Generated: createAsset(
    "page-film-wedding-photography-gallery-6",
    "/images/brand/page-generated/page-film-wedding-photography-gallery-6.webp",
    "A Hasselblad 500cm on a stone windowsill above a Tuscan wedding garden.",
    1024,
    1536,
    "sage",
  ),
  villaRaffaelliHeroPrimaryGenerated: createAsset(
    "page-villa-raffaelli-hero-primary",
    "/images/brand/page-generated/page-villa-raffaelli-hero-primary.webp",
    "Two people exchanging private wedding vows in the courtyard of Villa Raffaelli.",
    1600,
    900,
    "stone",
  ),
  villaRaffaelliHeroSecondaryGenerated: createAsset(
    "page-villa-raffaelli-hero-secondary",
    "/images/brand/page-generated/page-villa-raffaelli-hero-secondary.webp",
    "Morning light crossing the facade of Villa Raffaelli.",
    1600,
    900,
    "linen",
  ),
  villaRaffaelliHeroTertiaryGenerated: createAsset(
    "page-villa-raffaelli-hero-tertiary",
    "/images/brand/page-generated/page-villa-raffaelli-hero-tertiary.webp",
    "Two newly married partners walking through the Villa Raffaelli garden with Garfagnana mountains behind them.",
    1600,
    900,
    "sage",
  ),
  villaRaffaelliHeroQuaternaryGenerated: createAsset(
    "page-villa-raffaelli-hero-quaternary",
    "/images/brand/page-generated/page-villa-raffaelli-hero-quaternary.webp",
    "A couple in the library world of Villa Raffaelli in soft morning light.",
    1600,
    900,
    "stone",
  ),
  villaRaffaelliGallery1Generated: createAsset(
    "page-villa-raffaelli-gallery-1",
    "/images/brand/page-generated/page-villa-raffaelli-gallery-1.webp",
    "Two people exchanging private wedding vows in the courtyard of Villa Raffaelli.",
    1536,
    1024,
    "stone",
  ),
  villaRaffaelliGallery2Generated: createAsset(
    "page-villa-raffaelli-gallery-2",
    "/images/brand/page-generated/page-villa-raffaelli-gallery-2.webp",
    "Two newly married partners walking through the Villa Raffaelli garden with Garfagnana mountains behind them.",
    1024,
    1536,
    "sage",
  ),
  villaRaffaelliGallery3Generated: createAsset(
    "page-villa-raffaelli-gallery-3",
    "/images/brand/page-generated/page-villa-raffaelli-gallery-3.webp",
    "Morning light crossing the facade of Villa Raffaelli.",
    1024,
    1536,
    "linen",
  ),
  contactCraftImageGenerated: createAsset(
    "page-contact-craft-image",
    "/images/brand/page-generated/page-contact-craft-image.webp",
    "A Rolleiflex camera on a bridal preparation table with silk details and morning light.",
    1120,
    1400,
    "linen",
  ),
  sharedTeamWiderStudioGenerated: createAsset(
    "shared-team-wider-studio",
    "/images/brand/page-generated/shared-team-wider-studio.webp",
    "A monochrome architectural sketch of Villa Raffaelli above Tuscan stone steps.",
    1120,
    1400,
    "stone",
  ),
} as const;

export type ImageAssetLibraryKey = keyof typeof imageAssetLibrary;

export function getImageLibraryAsset(
  id: ImageAssetLibraryKey,
): ImageLibraryAsset {
  return imageAssetLibrary[id];
}
